### PR TITLE
A hell lot of changes

### PR DESCRIPTION
**Pull request by ankurpandeyvns**

### CODE REVIEW

**Comment by Herzfinsternis** [comment]
**system.prop:**
Is [this bug](https://jira.lineageos.org/browse/BUGBASH-291) fixed?
My solution was adding `qemu.sf.lcd_density=480` to the build.prop on my phone. This should go into [system.prop](https://github.com/LineageOS/android_device_zuk_ham/blob/cm-14.1/system.prop) in source?
The bug can be verified by [Display Metrics Info](https://play.google.com/store/apps/details?id=com.noser.android.apps.tools), which should report 480 dpi.

**[README.md](https://github.com/LineageOS/android_device_zuk_ham/pull/5/commits/ff84f92ad967902c825d90347bdaf062de7f158e#diff-04c6e90faac2675aa89e2176d2eec7d8):**
http://cdn2.gsmarena.com/vv/pics/lenovo/lenovo-zuk-z1-1.jpg has a watermark from GSMArena. It is probably not allowed to use that picture.

Thanks for the work...

**Comment by ankurpandeyvns** [comment]
This bug isn't present on this device tree.

**Comment by ashwinss** [comment]
hey - are your changes merged to LineageOS:cm-14.1 ?

**Comment by ankurpandeyvns** [comment]
Nope

**Pull request closed without merging**
